spring:
  datasource:
#    url: jdbc:mysql://172.28.128.4:3306/WebShop?useSSL=false
#    username: root
#    password: my-secret-pw
#    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:./.data/h2/db;MODE=MySQL
    username: 
    password: 
    driverClassName: org.h2.Driver
#
mybatis:
  mapper-locations: "classpath:com/xlbean/**/dao/mapper/**/*.xml"
  type-handlers-package: "com.xlbean.xlgenapp.dao.typehandler"
   
